# Generated by Django 3.2 on 2021-05-02 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hudebniny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Druh zboží',
                'verbose_name_plural': 'Druhy zboží',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Vyrobce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název')),
            ],
            options={
                'verbose_name': 'Výrobce',
                'verbose_name_plural': 'Výrobci',
                'ordering': ['nazev'],
            },
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['-cena', 'nazev'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produkt/%Y/%m/%d/', verbose_name='Fotka produktu'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazev',
            field=models.CharField(max_length=100, unique=True, verbose_name='Název'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='vyrobce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hudebniny.vyrobce'),
            preserve_default=False,
        ),
    ]
