# Generated by Django 3.2 on 2021-05-02 16:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hudebniny', '0002_auto_20210502_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='druh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hudebniny.druh'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena'),
        ),
    ]
