# Generated by Django 3.2 on 2021-05-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hudebniny', '0004_druh_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='popis',
            field=models.TextField(default=1, verbose_name='Popis'),
            preserve_default=False,
        ),
    ]
